name: Deploy
on:
  pull_request:
    types: [labeled]

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    if: ${{ github.event.label.name == 'deploy' }}
    steps:
    - uses: actions/checkout@v1

    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'swish-app'
        namespace: 'default'
        chart: 'swish-app'
        token: '${{ secrets.GH_TOKEN }}'
        values: |
          name: foobar
        value-files: >-
        [
        # by deploying with helm we ave the ability specify al the values right in the repo
          "values.yaml",
        ]
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'